// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARBxFx0wGfOLzF4lIJOO2pZ87FbUhycvU',
    appId: '1:805489089422:web:6dea6d712d34af6933e2df',
    messagingSenderId: '805489089422',
    projectId: 'coiffure-salon',
    authDomain: 'coiffure-salon.firebaseapp.com',
    storageBucket: 'coiffure-salon.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAha8SV2bHtXTMlspg4Jbryb8DcyaBcty0',
    appId: '1:805489089422:android:892f895414ba0fba33e2df',
    messagingSenderId: '805489089422',
    projectId: 'coiffure-salon',
    storageBucket: 'coiffure-salon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtzG7dvRae-Th52119r98tyAEo8rG_1bM',
    appId: '1:805489089422:ios:daf4cc4f3639e21633e2df',
    messagingSenderId: '805489089422',
    projectId: 'coiffure-salon',
    storageBucket: 'coiffure-salon.firebasestorage.app',
    iosBundleId: 'com.example.soifapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtzG7dvRae-Th52119r98tyAEo8rG_1bM',
    appId: '1:805489089422:ios:daf4cc4f3639e21633e2df',
    messagingSenderId: '805489089422',
    projectId: 'coiffure-salon',
    storageBucket: 'coiffure-salon.firebasestorage.app',
    iosBundleId: 'com.example.soifapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARBxFx0wGfOLzF4lIJOO2pZ87FbUhycvU',
    appId: '1:805489089422:web:5e8988d8ac4d13f233e2df',
    messagingSenderId: '805489089422',
    projectId: 'coiffure-salon',
    authDomain: 'coiffure-salon.firebaseapp.com',
    storageBucket: 'coiffure-salon.firebasestorage.app',
  );
}
